# Generated by Django 5.2.7 on 2025-10-05 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('OPEN', 'Open Workspace'), ('DEEP', 'Deep Work'), ('CHILL', 'Chill'), ('KITCH', 'Kitchen'), ('CONF', 'Conference')], default='OPEN', max_length=5)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('has_dock', models.BooleanField(default=False)),
                ('has_adjustable_desk', models.BooleanField(default=False)),
                ('has_dual_monitors', models.BooleanField(default=False)),
                ('is_deep_work', models.BooleanField(default=False)),
                ('x_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('y_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.floor')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.desk')),
            ],
            options={
                'unique_together': {('desk', 'date', 'time_from', 'time_to')},
            },
        ),
    ]
