# Generated by Django 5.2.7 on 2025-10-19 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('image_path', models.CharField(default='floorplans/floor4.png', help_text='Ścieżka do pliku z planem piętra', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('REMINDER', 'Przypomnienie o rezerwacji'), ('CANCELLATION', 'Anulowanie rezerwacji'), ('WAITLIST', 'Powiadomienie z waitlist'), ('DAILY_SUMMARY', 'Dzienne podsumowanie'), ('WEEKLY_REPORT', 'Tygodniowy raport'), ('CONFIRMATION', 'Potwierdzenie rezerwacji')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('has_dock', models.BooleanField(default=False)),
                ('has_adjustable_desk', models.BooleanField(default=False)),
                ('has_dual_monitors', models.BooleanField(default=False)),
                ('is_deep_work', models.BooleanField(default=False)),
                ('x_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('y_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.floor')),
            ],
        ),
        migrations.CreateModel(
            name='GroupReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=120)),
                ('organizer_email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desks', models.ManyToManyField(related_name='group_reservations', to='reservations.desk')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('endpoint', models.URLField()),
                ('p256dh_key', models.CharField(max_length=255)),
                ('auth_key', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('email', 'endpoint')},
            },
        ),
        migrations.CreateModel(
            name='RecurringReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('frequency', models.CharField(choices=[('DAILY', 'Codziennie'), ('WEEKLY', 'Tygodniowo'), ('MONTHLY', 'Miesięcznie')], default='DAILY', max_length=10)),
                ('days_of_week', models.CharField(default='1111111', help_text='1=Monday, 7=Sunday', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_reservations', to='reservations.desk')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('preferred_dock', models.BooleanField(default=False)),
                ('preferred_dual_monitors', models.BooleanField(default=False)),
                ('preferred_adjustable_desk', models.BooleanField(default=False)),
                ('preferred_deep_work', models.BooleanField(default=False)),
                ('email_notifications', models.BooleanField(default=True)),
                ('reminder_before_booking', models.IntegerField(default=30, help_text='Przypomnienie X minut przed rezerwacją')),
                ('daily_summary', models.BooleanField(default=True)),
                ('weekly_report', models.BooleanField(default=False)),
                ('waitlist_notifications', models.BooleanField(default=True)),
                ('cancellation_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_date', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='reservations.desk')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('OPEN', 'Open Workspace'), ('DEEP', 'Deep Work'), ('CHILL', 'Chill'), ('KITCH', 'Kitchen'), ('CONF', 'Conference')], default='OPEN', max_length=5)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.floor')),
            ],
        ),
        migrations.AddField(
            model_name='desk',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.zone'),
        ),
        migrations.CreateModel(
            name='ConferenceRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(default=4)),
                ('description', models.TextField(blank=True)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_whiteboard', models.BooleanField(default=False)),
                ('has_video_conference', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.floor')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.zone')),
            ],
        ),
        migrations.CreateModel(
            name='ConferenceReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=120)),
                ('contact_email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('attendees_count', models.IntegerField(default=1)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conference_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.conferenceroom')),
            ],
            options={
                'unique_together': {('conference_room', 'date', 'time_from', 'time_to')},
            },
        ),
        migrations.CreateModel(
            name='DeskBookingLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('locked_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.desk')),
            ],
            options={
                'unique_together': {('desk', 'email')},
            },
        ),
        migrations.CreateModel(
            name='GuestReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=120)),
                ('guest_email', models.EmailField(max_length=254)),
                ('host_name', models.CharField(max_length=120)),
                ('host_email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_reservations', to='reservations.desk')),
            ],
            options={
                'unique_together': {('desk', 'date', 'time_from', 'time_to')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.desk')),
            ],
            options={
                'unique_together': {('desk', 'date', 'time_from', 'time_to')},
            },
        ),
    ]
