# Generated by Django 5.2.5 on 2025-10-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='image_path',
            field=models.CharField(default='floorplans/floor4.png', help_text='Ścieżka do pliku z planem piętra', max_length=200),
        ),
    ]
