# Generated by Django 5.2.5 on 2025-10-09 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_cancelled_at_reservation_is_cancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('preferred_dock', models.BooleanField(default=False)),
                ('preferred_dual_monitors', models.BooleanField(default=False)),
                ('preferred_adjustable_desk', models.BooleanField(default=False)),
                ('preferred_deep_work', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_floor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.floor')),
            ],
        ),
        migrations.CreateModel(
            name='DeskBookingLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('locked_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.desk')),
            ],
            options={
                'unique_together': {('desk', 'email')},
            },
        ),
    ]
