# Generated by Django 5.2.5 on 2025-10-09 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_recurringreservation_teamroom_waitlist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('type', models.CharField(choices=[('REMINDER', 'Przypomnienie o rezerwacji'), ('CANCELLATION', 'Anulowanie rezerwacji'), ('WAITLIST', 'Powiadomienie z waitlist'), ('DAILY_SUMMARY', 'Dzienne podsumowanie'), ('WEEKLY_REPORT', 'Tygodniowy raport'), ('CONFIRMATION', 'Potwierdzenie rezerwacji')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='cancellation_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='daily_summary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='reminder_before_booking',
            field=models.IntegerField(default=30, help_text='Przypomnienie X minut przed rezerwacją'),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='waitlist_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='weekly_report',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('endpoint', models.URLField()),
                ('p256dh_key', models.CharField(max_length=255)),
                ('auth_key', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('email', 'endpoint')},
            },
        ),
    ]
