# Generated by Django 5.2.5 on 2025-10-09 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=120)),
                ('organizer_email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('desks', models.ManyToManyField(related_name='group_reservations', to='reservations.desk')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
