# Generated by Django 5.2.5 on 2025-10-15 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_conferenceroom_conferencereservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamroom',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='teamroom',
            name='zone',
        ),
        migrations.DeleteModel(
            name='TeamReservation',
        ),
        migrations.DeleteModel(
            name='TeamRoom',
        ),
    ]
